### ISSUE TITLE
Could you please also share Google Drive link for downloading?

### ISSUE THREAD

**Issue by Ir1d** [XUHUAKing/CDR-download-scripts#1]
Hi, thank you for sharing this dataset. When downloading, I keep getting such error messages and couldn't download the whole dataset. It'll be great if Google Drive link could also be provided.
![image](https://user-images.githubusercontent.com/10709657/146492576-c0a5cc61-0375-4412-9792-47a47ce2b1d6.png)

**Comment by XUHUAKing** [comment]
Hi, thanks for using our dataset! Due to storage limitation we are not able to provide google drive link now (but we will try to release it asap). OneDrive might have some issues when downloading large file from the webpage, I have tried using a open source tool called [rclone](https://rclone.org/onedrive/) which can connect the OneDrive and download large file with commands. You may have a try.

**Comment by Ir1d** [comment]
@XUHUAKing Thank you. But does rclone support downloading from shared folders? I think rclone can only be used to download  files owned by my account.

**Comment by XUHUAKing** [comment]
@Ir1d Is it possible to copy the folder to your own account first?

**Comment by Ir1d** [comment]
@XUHUAKing I don't think so. :joy:

**Comment by XUHUAKing** [comment]
Hi @Ir1d, one of us tried to add a shortcut in his own account pointing to the original data folder, and successfully downloaded with `rclone`

**Comment by Ir1d** [comment]
@XUHUAKing Thank you so much! Is he using his private ms account, or using a work / school account?

**Comment by XUHUAKing** [comment]
Hi @Ir1d, he used a school account. I have uploaded the data to google drive in this [link](https://drive.google.com/drive/folders/1zl-5QFmexdirHMKtiY-S1d87yK5MzdWk?usp=sharing).
